### PR TITLE
Optimize shadow stack instruction sequences

### PR DESCRIPTION
**Pull request by Robbepop**
Closes https://github.com/paritytech/wasmi/issues/920.

## TODOs

- [x] Fuse `i32.add_imm` with `global.set 0`
- [x] Fuse `global.get 0` with `i32.add_imm`
- [x] Fuse fused `global.get 0` + `i32.add_imm` with `i32.local_tee` and `global.set 0`
- [x] Support fusion of `i32.add` with a function local constant `rhs` register.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 1.64ms</td> <td nowrap> 1.56ms</td> <td nowrap> :green_circle: -4.47%</td> <td nowrap> 1.34ms</td> <td nowrap> 1.32ms</td> <td nowrap> :green_circle: -1.74%</td> <td nowrap> :green_circle: -15%</td></tr><tr><td><tt>execute/</tt><br><tt>call/host/1</td> <td nowrap> 51.45µs</td> <td nowrap> 51.93µs</td> <td nowrap> :white_circle: 0.93%</td> <td nowrap> 61.67µs</td> <td nowrap> 57.56µs</td> <td nowrap> :green_circle: -6.67%</td> <td nowrap> :green_circle: 11%</td></tr><tr><td><tt>execute/</tt><br><tt>call/rec</td> <td nowrap> 175.93µs</td> <td nowrap> 169.28µs</td> <td nowrap> :green_circle: -3.78%</td> <td nowrap> 291.12µs</td> <td nowrap> 291.89µs</td> <td nowrap> :white_circle: 0.26%</td> <td nowrap> :yellow_circle: 72%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 5.79ms</td> <td nowrap> 5.42ms</td> <td nowrap> :green_circle: -6.41%</td> <td nowrap> 7.23ms</td> <td nowrap> 7.24ms</td> <td nowrap> :white_circle: 0.16%</td> <td nowrap> :green_circle: 34%</td></tr><tr><td><tt>execute/</tt><br><tt>divrem</td> <td nowrap> 6.25ms</td> <td nowrap> 6.32ms</td> <td nowrap> :white_circle: 1.01%</td> <td nowrap> 6.32ms</td> <td nowrap> 6.30ms</td> <td nowrap> :white_circle: -0.24%</td> <td nowrap> :green_circle: -0%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial/iter</td> <td nowrap> 263.77µs</td> <td nowrap> 253.57µs</td> <td nowrap> :green_circle: -3.87%</td> <td nowrap> 282.78µs</td> <td nowrap> 267.16µs</td> <td nowrap> :green_circle: -5.52%</td> <td nowrap> :green_circle: 5%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial/rec</td> <td nowrap> 665.67µs</td> <td nowrap> 668.89µs</td> <td nowrap> :white_circle: 0.48%</td> <td nowrap> 1.09ms</td> <td nowrap> 1.06ms</td> <td nowrap> :green_circle: -2.71%</td> <td nowrap> :yellow_circle: 58%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci/iter</td> <td nowrap> 1.33ms</td> <td nowrap> 1.33ms</td> <td nowrap> :white_circle: -0.62%</td> <td nowrap> 1.13ms</td> <td nowrap> 1.15ms</td> <td nowrap> :red_circle: 1.33%</td> <td nowrap> :green_circle: -13%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci/rec</td> <td nowrap> 5.81ms</td> <td nowrap> 5.79ms</td> <td nowrap> :white_circle: -0.29%</td> <td nowrap> 10.70ms</td> <td nowrap> 10.97ms</td> <td nowrap> :red_circle: 2.52%</td> <td nowrap> :yellow_circle: 89%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci/tail</td> <td nowrap> 1.28ms</td> <td nowrap> 1.33ms</td> <td nowrap> :red_circle: 3.83%</td> <td nowrap> 3.84ms</td> <td nowrap> 3.60ms</td> <td nowrap> :green_circle: -6.22%</td> <td nowrap> :red_circle: 172%</td></tr><tr><td><tt>execute/</tt><br><tt>fuse</td> <td nowrap> 7.07ms</td> <td nowrap> 7.14ms</td> <td nowrap> :white_circle: 1.02%</td> <td nowrap> 11.17ms</td> <td nowrap> 11.18ms</td> <td nowrap> :white_circle: 0.11%</td> <td nowrap> :yellow_circle: 57%</td></tr><tr><td><tt>execute/</tt><br><tt>global/bump</td> <td nowrap> 1.32ms</td> <td nowrap> 1.15ms</td> <td nowrap> :green_circle: -12.60%</td> <td nowrap> 1.45ms</td> <td nowrap> 1.34ms</td> <td nowrap> :green_circle: -8.08%</td> <td nowrap> :green_circle: 16%</td></tr><tr><td><tt>execute/</tt><br><tt>global/get_const</td> <td nowrap> 479.87µs</td> <td nowrap> 483.34µs</td> <td nowrap> :white_circle: 0.72%</td> <td nowrap> 726.54µs</td> <td nowrap> 726.83µs</td> <td nowrap> :white_circle: 0.04%</td> <td nowrap> :green_circle: 50%</td></tr><tr><td><tt>execute/</tt><br><tt>is_even/rec</td> <td nowrap> 1.10ms</td> <td nowrap> 1.10ms</td> <td nowrap> :white_circle: -0.29%</td> <td nowrap> 1.81ms</td> <td nowrap> 1.82ms</td> <td nowrap> :white_circle: 0.45%</td> <td nowrap> :yellow_circle: 66%</td></tr><tr><td><tt>execute/</tt><br><tt>memory/fill_bytes</td> <td nowrap> 1.09ms</td> <td nowrap> 1.14ms</td> <td nowrap> :red_circle: 5.02%</td> <td nowrap> 1.21ms</td> <td nowrap> 1.19ms</td> <td nowrap> :green_circle: -1.56%</td> <td nowrap> :green_circle: 4%</td></tr><tr><td><tt>execute/</tt><br><tt>memory/sum_bytes</td> <td nowrap> 1.05ms</td> <td nowrap> 1.12ms</td> <td nowrap> :red_circle: 6.88%</td> <td nowrap> 1.39ms</td> <td nowrap> 1.23ms</td> <td nowrap> :green_circle: -11.31%</td> <td nowrap> :green_circle: 10%</td></tr><tr><td><tt>execute/</tt><br><tt>memory/vec_add</td> <td nowrap> 2.98ms</td> <td nowrap> 3.07ms</td> <td nowrap> :white_circle: 3.32%</td> <td nowrap> 3.22ms</td> <td nowrap> 3.20ms</td> <td nowrap> :white_circle: -0.67%</td> <td nowrap> :green_circle: 4%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 191.27µs</td> <td nowrap> 188.57µs</td> <td nowrap> :green_circle: -1.42%</td> <td nowrap> 309.19µs</td> <td nowrap> 308.99µs</td> <td nowrap> :white_circle: -0.06%</td> <td nowrap> :yellow_circle: 64%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 16.09µs</td> <td nowrap> 15.73µs</td> <td nowrap> :green_circle: -2.23%</td> <td nowrap> 27.59µs</td> <td nowrap> 27.22µs</td> <td nowrap> :green_circle: -1.34%</td> <td nowrap> :yellow_circle: 73%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 585.99µs</td> <td nowrap> 590.37µs</td> <td nowrap> :white_circle: 0.75%</td> <td nowrap> 999.71µs</td> <td nowrap> 983.13µs</td> <td nowrap> :green_circle: -1.66%</td> <td nowrap> :yellow_circle: 67%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 438.70µs</td> <td nowrap> 434.32µs</td> <td nowrap> :white_circle: -1.00%</td> <td nowrap> 620.11µs</td> <td nowrap> 610.22µs</td> <td nowrap> :green_circle: -1.60%</td> <td nowrap> :green_circle: 40%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 350.28µs</td> <td nowrap> 349.78µs</td> <td nowrap> :white_circle: -0.15%</td> <td nowrap> 318.71µs</td> <td nowrap> 348.34µs</td> <td nowrap> :red_circle: 9.30%</td> <td nowrap> :green_circle: -0%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 630.07µs</td> <td nowrap> 635.42µs</td> <td nowrap> :white_circle: 0.85%</td> <td nowrap> 931.31µs</td> <td nowrap> 946.71µs</td> <td nowrap> :red_circle: 1.65%</td> <td nowrap> :green_circle: 49%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 54.88µs</td> <td nowrap> 56.86µs</td> <td nowrap> :red_circle: 3.61%</td> <td nowrap> 55.94µs</td> <td nowrap> 57.04µs</td> <td nowrap> :white_circle: 1.97%</td> <td nowrap> :green_circle: 0%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/typed/0</td> <td nowrap> 1.24ms</td> <td nowrap> 1.25ms</td> <td nowrap> :white_circle: 0.60%</td> <td nowrap> 964.09µs</td> <td nowrap> 825.92µs</td> <td nowrap> :green_circle: -14.33%</td> <td nowrap> :green_circle: -34%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/typed/16</td> <td nowrap> 1.64ms</td> <td nowrap> 1.65ms</td> <td nowrap> :white_circle: 0.97%</td> <td nowrap> 2.23ms</td> <td nowrap> 2.07ms</td> <td nowrap> :green_circle: -6.98%</td> <td nowrap> :green_circle: 26%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/untyped/0</td> <td nowrap> 1.59ms</td> <td nowrap> 1.58ms</td> <td nowrap> :white_circle: -0.79%</td> <td nowrap> 1.16ms</td> <td nowrap> 1.17ms</td> <td nowrap> :white_circle: 0.64%</td> <td nowrap> :green_circle: -26%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/untyped/16</td> <td nowrap> 2.44ms</td> <td nowrap> 2.51ms</td> <td nowrap> :red_circle: 2.57%</td> <td nowrap> 3.84ms</td> <td nowrap> 4.20ms</td> <td nowrap> :red_circle: 9.41%</td> <td nowrap> :yellow_circle: 68%</td></tr><tr><td><tt>translate/</tt><br><tt>bz2/checked/eager/default</td> <td nowrap> 1.36ms</td> <td nowrap> 1.35ms</td> <td nowrap> :white_circle: -0.83%</td> <td nowrap> 2.46ms</td> <td nowrap> 2.44ms</td> <td nowrap> :white_circle: -0.72%</td> <td nowrap> :yellow_circle: 81%</td></tr><tr><td><tt>translate/</tt><br><tt>bz2/checked/eager/fuel</td> <td nowrap> 1.46ms</td> <td nowrap> 1.45ms</td> <td nowrap> :white_circle: -0.51%</td> <td nowrap> 2.66ms</td> <td nowrap> 2.65ms</td> <td nowrap> :white_circle: -0.40%</td> <td nowrap> :yellow_circle: 83%</td></tr><tr><td><tt>translate/</tt><br><tt>bz2/checked/lazy-translation/default</td> <td nowrap> 545.42µs</td> <td nowrap> 544.19µs</td> <td nowrap> :white_circle: -0.23%</td> <td nowrap> 957.58µs</td> <td nowrap> 966.15µs</td> <td nowrap> :white_circle: 0.90%</td> <td nowrap> :yellow_circle: 78%</td></tr><tr><td><tt>translate/</tt><br><tt>bz2/checked/lazy/default</td> <td nowrap> 37.20µs</td> <td nowrap> 36.83µs</td> <td nowrap> :white_circle: -0.98%</td> <td nowrap> 45.65µs</td> <td nowrap> 45.16µs</td> <td nowrap> :white_circle: -1.08%</td> <td nowrap> :green_circle: 23%</td></tr><tr><td><tt>translate/</tt><br><tt>bz2/unchecked/eager/default</td> <td nowrap> 1.10ms</td> <td nowrap> 1.09ms</td> <td nowrap> :white_circle: -0.67%</td> <td nowrap> 1.99ms</td> <td nowrap> 1.87ms</td> <td nowrap> :green_circle: -5.89%</td> <td nowrap> :yellow_circle: 71%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155/checked/eager/default</td> <td nowrap> 283.68µs</td> <td nowrap> 282.14µs</td> <td nowrap> :white_circle: -0.54%</td> <td nowrap> 480.54µs</td> <td nowrap> 474.73µs</td> <td nowrap> :white_circle: -1.21%</td> <td nowrap> :yellow_circle: 68%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155/checked/eager/fuel</td> <td nowrap> 302.90µs</td> <td nowrap> 303.77µs</td> <td nowrap> :white_circle: 0.29%</td> <td nowrap> 512.70µs</td> <td nowrap> 509.92µs</td> <td nowrap> :white_circle: -0.54%</td> <td nowrap> :yellow_circle: 68%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155/checked/lazy-translation/default</td> <td nowrap> 127.47µs</td> <td nowrap> 128.08µs</td> <td nowrap> :white_circle: 0.48%</td> <td nowrap> 211.67µs</td> <td nowrap> 211.19µs</td> <td nowrap> :white_circle: -0.22%</td> <td nowrap> :yellow_circle: 65%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155/checked/lazy/default</td> <td nowrap> 25.86µs</td> <td nowrap> 25.93µs</td> <td nowrap> :white_circle: 0.28%</td> <td nowrap> 32.67µs</td> <td nowrap> 32.41µs</td> <td nowrap> :white_circle: -0.81%</td> <td nowrap> :green_circle: 25%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155/unchecked/eager/default</td> <td nowrap> 232.37µs</td> <td nowrap> 229.14µs</td> <td nowrap> :green_circle: -1.39%</td> <td nowrap> 390.52µs</td> <td nowrap> 370.20µs</td> <td nowrap> :green_circle: -5.20%</td> <td nowrap> :yellow_circle: 62%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20/checked/eager/default</td> <td nowrap> 137.54µs</td> <td nowrap> 137.10µs</td> <td nowrap> :white_circle: -0.32%</td> <td nowrap> 230.53µs</td> <td nowrap> 227.33µs</td> <td nowrap> :white_circle: -1.39%</td> <td nowrap> :yellow_circle: 66%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20/checked/eager/fuel</td> <td nowrap> 144.72µs</td> <td nowrap> 144.69µs</td> <td nowrap> :white_circle: -0.02%</td> <td nowrap> 243.54µs</td> <td nowrap> 239.41µs</td> <td nowrap> :green_circle: -1.70%</td> <td nowrap> :yellow_circle: 65%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20/checked/lazy-translation/default</td> <td nowrap> 65.58µs</td> <td nowrap> 65.85µs</td> <td nowrap> :white_circle: 0.41%</td> <td nowrap> 107.21µs</td> <td nowrap> 107.68µs</td> <td nowrap> :white_circle: 0.44%</td> <td nowrap> :yellow_circle: 64%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20/checked/lazy/default</td> <td nowrap> 18.86µs</td> <td nowrap> 19.17µs</td> <td nowrap> :white_circle: 1.65%</td> <td nowrap> 24.46µs</td> <td nowrap> 24.79µs</td> <td nowrap> :red_circle: 1.32%</td> <td nowrap> :green_circle: 29%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20/unchecked/eager/default</td> <td nowrap> 113.52µs</td> <td nowrap> 111.60µs</td> <td nowrap> :green_circle: -1.69%</td> <td nowrap> 187.61µs</td> <td nowrap> 176.37µs</td> <td nowrap> :green_circle: -5.99%</td> <td nowrap> :yellow_circle: 58%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721/checked/eager/default</td> <td nowrap> 195.27µs</td> <td nowrap> 192.36µs</td> <td nowrap> :green_circle: -1.49%</td> <td nowrap> 333.24µs</td> <td nowrap> 326.76µs</td> <td nowrap> :green_circle: -1.94%</td> <td nowrap> :yellow_circle: 70%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721/checked/eager/fuel</td> <td nowrap> 204.56µs</td> <td nowrap> 202.04µs</td> <td nowrap> :green_circle: -1.23%</td> <td nowrap> 351.20µs</td> <td nowrap> 346.76µs</td> <td nowrap> :white_circle: -1.26%</td> <td nowrap> :yellow_circle: 72%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721/checked/lazy-translation/default</td> <td nowrap> 91.41µs</td> <td nowrap> 91.37µs</td> <td nowrap> :white_circle: -0.04%</td> <td nowrap> 154.11µs</td> <td nowrap> 152.72µs</td> <td nowrap> :white_circle: -0.90%</td> <td nowrap> :yellow_circle: 67%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721/checked/lazy/default</td> <td nowrap> 22.42µs</td> <td nowrap> 22.91µs</td> <td nowrap> :red_circle: 2.19%</td> <td nowrap> 28.57µs</td> <td nowrap> 29.03µs</td> <td nowrap> :red_circle: 1.61%</td> <td nowrap> :green_circle: 27%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721/unchecked/eager/default</td> <td nowrap> 156.61µs</td> <td nowrap> 155.91µs</td> <td nowrap> :white_circle: -0.45%</td> <td nowrap> 265.69µs</td> <td nowrap> 250.99µs</td> <td nowrap> :green_circle: -5.53%</td> <td nowrap> :yellow_circle: 61%</td></tr><tr><td><tt>translate/</tt><br><tt>pulldown_cmark/checked/eager/default</td> <td nowrap> 3.70ms</td> <td nowrap> 3.67ms</td> <td nowrap> :white_circle: -0.75%</td> <td nowrap> 6.25ms</td> <td nowrap> 6.20ms</td> <td nowrap> :white_circle: -0.84%</td> <td nowrap> :yellow_circle: 69%</td></tr><tr><td><tt>translate/</tt><br><tt>pulldown_cmark/checked/eager/fuel</td> <td nowrap> 4.02ms</td> <td nowrap> 3.94ms</td> <td nowrap> :green_circle: -1.81%</td> <td nowrap> 6.73ms</td> <td nowrap> 6.68ms</td> <td nowrap> :white_circle: -0.82%</td> <td nowrap> :yellow_circle: 69%</td></tr><tr><td><tt>translate/</tt><br><tt>pulldown_cmark/checked/lazy-translation/default</td> <td nowrap> 1.55ms</td> <td nowrap> 1.54ms</td> <td nowrap> :white_circle: -0.59%</td> <td nowrap> 2.58ms</td> <td nowrap> 2.59ms</td> <td nowrap> :white_circle: 0.10%</td> <td nowrap> :yellow_circle: 67%</td></tr><tr><td><tt>translate/</tt><br><tt>pulldown_cmark/checked/lazy/default</td> <td nowrap> 244.85µs</td> <td nowrap> 257.23µs</td> <td nowrap> :red_circle: 5.05%</td> <td nowrap> 250.35µs</td> <td nowrap> 253.01µs</td> <td nowrap> :white_circle: 1.06%</td> <td nowrap> :green_circle: -2%</td></tr><tr><td><tt>translate/</tt><br><tt>pulldown_cmark/unchecked/eager/default</td> <td nowrap> 3.09ms</td> <td nowrap> 3.06ms</td> <td nowrap> :white_circle: -0.98%</td> <td nowrap> 5.09ms</td> <td nowrap> 4.85ms</td> <td nowrap> :green_circle: -4.64%</td> <td nowrap> :yellow_circle: 58%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey/checked/eager/default</td> <td nowrap> 77.89ms</td> <td nowrap> 76.87ms</td> <td nowrap> :green_circle: -1.30%</td> <td nowrap> 135.34ms</td> <td nowrap> 134.48ms</td> <td nowrap> :white_circle: -0.64%</td> <td nowrap> :yellow_circle: 75%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey/checked/eager/fuel</td> <td nowrap> 84.31ms</td> <td nowrap> 83.20ms</td> <td nowrap> :green_circle: -1.32%</td> <td nowrap> 146.03ms</td> <td nowrap> 144.98ms</td> <td nowrap> :white_circle: -0.72%</td> <td nowrap> :yellow_circle: 74%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey/checked/lazy-translation/default</td> <td nowrap> 32.92ms</td> <td nowrap> 32.72ms</td> <td nowrap> :white_circle: -0.61%</td> <td nowrap> 55.45ms</td> <td nowrap> 56.08ms</td> <td nowrap> :white_circle: 1.14%</td> <td nowrap> :yellow_circle: 71%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey/checked/lazy/default</td> <td nowrap> 3.58ms</td> <td nowrap> 3.53ms</td> <td nowrap> :white_circle: -1.58%</td> <td nowrap> 3.74ms</td> <td nowrap> 3.79ms</td> <td nowrap> :white_circle: 1.16%</td> <td nowrap> :green_circle: 7%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey/unchecked/eager/default</td> <td nowrap> 64.65ms</td> <td nowrap> 63.95ms</td> <td nowrap> :white_circle: -1.10%</td> <td nowrap> 110.75ms</td> <td nowrap> 104.37ms</td> <td nowrap> :green_circle: -5.76%</td> <td nowrap> :yellow_circle: 63%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel/checked/eager/default</td> <td nowrap> 5.18ms</td> <td nowrap> 5.09ms</td> <td nowrap> :green_circle: -1.72%</td> <td nowrap> 8.81ms</td> <td nowrap> 8.70ms</td> <td nowrap> :green_circle: -1.25%</td> <td nowrap> :yellow_circle: 71%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel/checked/eager/fuel</td> <td nowrap> 5.32ms</td> <td nowrap> 5.24ms</td> <td nowrap> :green_circle: -1.44%</td> <td nowrap> 9.28ms</td> <td nowrap> 9.14ms</td> <td nowrap> :green_circle: -1.47%</td> <td nowrap> :yellow_circle: 74%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel/checked/lazy-translation/default</td> <td nowrap> 2.45ms</td> <td nowrap> 2.43ms</td> <td nowrap> :white_circle: -0.82%</td> <td nowrap> 3.96ms</td> <td nowrap> 4.02ms</td> <td nowrap> :red_circle: 1.51%</td> <td nowrap> :yellow_circle: 66%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel/checked/lazy/default</td> <td nowrap> 421.33µs</td> <td nowrap> 433.50µs</td> <td nowrap> :red_circle: 2.89%</td> <td nowrap> 477.90µs</td> <td nowrap> 493.58µs</td> <td nowrap> :red_circle: 3.28%</td> <td nowrap> :green_circle: 14%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel/unchecked/eager/default</td> <td nowrap> 4.17ms</td> <td nowrap> 4.14ms</td> <td nowrap> :white_circle: -0.67%</td> <td nowrap> 6.99ms</td> <td nowrap> 6.68ms</td> <td nowrap> :green_circle: -4.40%</td> <td nowrap> :yellow_circle: 61%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/5136739)

**Comment by Robbepop** [comment]
Comment on why this has not yet been merged despite passing all CI tests and working: it introduces a lot of complexity into the translation pipelined compared to the gains we see and can verify. The runtime gains are mostly single digits and restricted to sets of benchmarks that actually make use of the shadow stack. The `global_bump` benchmark is heavily affected with roughly 30% performance improvement but it is also very artificial. On the flip side the improvements to memory consumption also exist but are also just single digits for practical Wasm binaries.

So all in all the question is if the gains are worth the added complexities.

**Comment by Robbepop** [comment]
The `miri` CI job fails because of this issue: https://github.com/rust-lang/miri/issues/3404

**Comment by Robbepop** [comment]
We might want to block this until we have multiple look-back translation feature in the Wasmi bytecode translator. This allows to get rid of intermediate optimized instructions.

**Comment by Robbepop** [comment]
I am closing this now since too much has happened in the code base so that a full rewrite would make more sense. However, I am very uncertain that this optimization is a clear improvement to Wasmi as a whole.

**Pull request closed without merging**
