### PR TITLE
Remove duplicated checks during instantiation

### PR DESCRIPTION
**Pull request by yjhmelody**
It seems that these checks are not necessary.
It's duplicated with `process_import`.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 1.53ms</td> <td nowrap> 1.52ms</td> <td nowrap> :white_circle: -0.34%</td> <td nowrap> 1.27ms</td> <td nowrap> 1.32ms</td> <td nowrap> :red_circle: 2.25%</td> <td nowrap> :green_circle: -13%</td></tr><tr><td><tt>execute/</tt><br><tt>call/host/1</td> <td nowrap> 36.99µs</td> <td nowrap> 36.08µs</td> <td nowrap> :green_circle: -2.48%</td> <td nowrap> 41.27µs</td> <td nowrap> 40.43µs</td> <td nowrap> :green_circle: -1.99%</td> <td nowrap> :green_circle: 12%</td></tr><tr><td><tt>execute/</tt><br><tt>call/rec</td> <td nowrap> 167.42µs</td> <td nowrap> 167.13µs</td> <td nowrap> :white_circle: -0.19%</td> <td nowrap> 363.44µs</td> <td nowrap> 362.48µs</td> <td nowrap> :white_circle: -0.10%</td> <td nowrap> :red_circle: 117%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 7.43ms</td> <td nowrap> 7.22ms</td> <td nowrap> :green_circle: -3.03%</td> <td nowrap> 7.63ms</td> <td nowrap> 7.74ms</td> <td nowrap> :white_circle: 2.81%</td> <td nowrap> :green_circle: 7%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial/iter</td> <td nowrap> 250.64µs</td> <td nowrap> 213.67µs</td> <td nowrap> :green_circle: -13.89%</td> <td nowrap> 309.69µs</td> <td nowrap> 296.25µs</td> <td nowrap> :green_circle: -4.40%</td> <td nowrap> :green_circle: 39%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial/rec</td> <td nowrap> 722.51µs</td> <td nowrap> 682.97µs</td> <td nowrap> :green_circle: -5.50%</td> <td nowrap> 1.32ms</td> <td nowrap> 1.32ms</td> <td nowrap> :white_circle: 0.06%</td> <td nowrap> :yellow_circle: 94%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci/iter</td> <td nowrap> 1.33ms</td> <td nowrap> 1.38ms</td> <td nowrap> :red_circle: 3.77%</td> <td nowrap> 1.27ms</td> <td nowrap> 1.27ms</td> <td nowrap> :white_circle: 0.17%</td> <td nowrap> :green_circle: -8%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci/rec</td> <td nowrap> 6.09ms</td> <td nowrap> 6.15ms</td> <td nowrap> :white_circle: 0.92%</td> <td nowrap> 13.04ms</td> <td nowrap> 13.55ms</td> <td nowrap> :red_circle: 3.96%</td> <td nowrap> :red_circle: 120%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci/tail</td> <td nowrap> 1.34ms</td> <td nowrap> 1.36ms</td> <td nowrap> :red_circle: 1.40%</td> <td nowrap> 4.01ms</td> <td nowrap> 3.72ms</td> <td nowrap> :green_circle: -7.27%</td> <td nowrap> :red_circle: 174%</td></tr><tr><td><tt>execute/</tt><br><tt>fuse</td> <td nowrap> 7.25ms</td> <td nowrap> 7.73ms</td> <td nowrap> :red_circle: 5.40%</td> <td nowrap> 12.61ms</td> <td nowrap> 12.87ms</td> <td nowrap> :red_circle: 2.09%</td> <td nowrap> :yellow_circle: 67%</td></tr><tr><td><tt>execute/</tt><br><tt>global/bump</td> <td nowrap> 1.32ms</td> <td nowrap> 1.32ms</td> <td nowrap> :white_circle: -0.37%</td> <td nowrap> 1.60ms</td> <td nowrap> 1.75ms</td> <td nowrap> :red_circle: 7.17%</td> <td nowrap> :green_circle: 33%</td></tr><tr><td><tt>execute/</tt><br><tt>global/get_const</td> <td nowrap> 711.58µs</td> <td nowrap> 726.07µs</td> <td nowrap> :red_circle: 2.03%</td> <td nowrap> 744.92µs</td> <td nowrap> 772.89µs</td> <td nowrap> :red_circle: 3.25%</td> <td nowrap> :green_circle: 6%</td></tr><tr><td><tt>execute/</tt><br><tt>is_even/rec</td> <td nowrap> 1.08ms</td> <td nowrap> 1.07ms</td> <td nowrap> :white_circle: -0.94%</td> <td nowrap> 2.24ms</td> <td nowrap> 2.27ms</td> <td nowrap> :white_circle: 1.02%</td> <td nowrap> :red_circle: 112%</td></tr><tr><td><tt>execute/</tt><br><tt>memory/fill_bytes</td> <td nowrap> 1.13ms</td> <td nowrap> 1.16ms</td> <td nowrap> :red_circle: 2.43%</td> <td nowrap> 1.23ms</td> <td nowrap> 1.23ms</td> <td nowrap> :white_circle: -0.11%</td> <td nowrap> :green_circle: 6%</td></tr><tr><td><tt>execute/</tt><br><tt>memory/sum_bytes</td> <td nowrap> 1.11ms</td> <td nowrap> 1.08ms</td> <td nowrap> :green_circle: -2.58%</td> <td nowrap> 1.23ms</td> <td nowrap> 1.23ms</td> <td nowrap> :white_circle: 0.15%</td> <td nowrap> :green_circle: 14%</td></tr><tr><td><tt>execute/</tt><br><tt>memory/vec_add</td> <td nowrap> 2.96ms</td> <td nowrap> 2.94ms</td> <td nowrap> :white_circle: -0.79%</td> <td nowrap> 3.56ms</td> <td nowrap> 3.54ms</td> <td nowrap> :white_circle: -0.63%</td> <td nowrap> :green_circle: 20%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 185.27µs</td> <td nowrap> 185.90µs</td> <td nowrap> :white_circle: 0.12%</td> <td nowrap> 377.98µs</td> <td nowrap> 383.81µs</td> <td nowrap> :red_circle: 1.59%</td> <td nowrap> :red_circle: 106%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 15.50µs</td> <td nowrap> 15.44µs</td> <td nowrap> :white_circle: -0.56%</td> <td nowrap> 36.91µs</td> <td nowrap> 36.38µs</td> <td nowrap> :white_circle: -1.24%</td> <td nowrap> :red_circle: 136%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 600.66µs</td> <td nowrap> 593.85µs</td> <td nowrap> :white_circle: -1.36%</td> <td nowrap> 1.09ms</td> <td nowrap> 1.08ms</td> <td nowrap> :white_circle: 1.98%</td> <td nowrap> :yellow_circle: 82%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 443.97µs</td> <td nowrap> 443.74µs</td> <td nowrap> :white_circle: 0.24%</td> <td nowrap> 646.38µs</td> <td nowrap> 690.14µs</td> <td nowrap> :red_circle: 9.16%</td> <td nowrap> :yellow_circle: 56%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 351.16µs</td> <td nowrap> 349.01µs</td> <td nowrap> :white_circle: -1.19%</td> <td nowrap> 383.42µs</td> <td nowrap> 400.89µs</td> <td nowrap> :red_circle: 4.36%</td> <td nowrap> :green_circle: 15%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 614.85µs</td> <td nowrap> 610.33µs</td> <td nowrap> :white_circle: -0.71%</td> <td nowrap> 948.70µs</td> <td nowrap> 968.96µs</td> <td nowrap> :white_circle: 0.98%</td> <td nowrap> :yellow_circle: 59%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 54.25µs</td> <td nowrap> 55.91µs</td> <td nowrap> :red_circle: 3.22%</td> <td nowrap> 56.82µs</td> <td nowrap> 59.03µs</td> <td nowrap> :white_circle: 2.63%</td> <td nowrap> :green_circle: 6%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/typed/0</td> <td nowrap> 1.22ms</td> <td nowrap> 1.24ms</td> <td nowrap> :white_circle: 1.22%</td> <td nowrap> 866.31µs</td> <td nowrap> 847.50µs</td> <td nowrap> :green_circle: -2.13%</td> <td nowrap> :green_circle: -31%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/typed/16</td> <td nowrap> 1.59ms</td> <td nowrap> 1.65ms</td> <td nowrap> :red_circle: 3.30%</td> <td nowrap> 1.92ms</td> <td nowrap> 2.00ms</td> <td nowrap> :red_circle: 4.01%</td> <td nowrap> :green_circle: 21%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/untyped/0</td> <td nowrap> 1.65ms</td> <td nowrap> 1.66ms</td> <td nowrap> :white_circle: 0.10%</td> <td nowrap> 1.43ms</td> <td nowrap> 1.35ms</td> <td nowrap> :green_circle: -5.38%</td> <td nowrap> :green_circle: -18%</td></tr><tr><td><tt>overhead/</tt><br><tt>call/untyped/16</td> <td nowrap> 2.49ms</td> <td nowrap> 2.41ms</td> <td nowrap> :green_circle: -3.36%</td> <td nowrap> 3.76ms</td> <td nowrap> 3.89ms</td> <td nowrap> :red_circle: 3.27%</td> <td nowrap> :yellow_circle: 61%</td></tr><tr><td><tt>translate/</tt><br><tt>bz2</td> <td nowrap> 1.31ms</td> <td nowrap> 1.32ms</td> <td nowrap> :white_circle: 0.67%</td> <td nowrap> 2.47ms</td> <td nowrap> 2.46ms</td> <td nowrap> :white_circle: -1.56%</td> <td nowrap> :yellow_circle: 87%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155</td> <td nowrap> 275.87µs</td> <td nowrap> 279.04µs</td> <td nowrap> :white_circle: 0.89%</td> <td nowrap> 476.04µs</td> <td nowrap> 506.90µs</td> <td nowrap> :red_circle: 5.17%</td> <td nowrap> :yellow_circle: 82%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20</td> <td nowrap> 133.80µs</td> <td nowrap> 136.84µs</td> <td nowrap> :red_circle: 2.06%</td> <td nowrap> 229.43µs</td> <td nowrap> 233.31µs</td> <td nowrap> :white_circle: 1.39%</td> <td nowrap> :yellow_circle: 71%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721</td> <td nowrap> 190.37µs</td> <td nowrap> 191.84µs</td> <td nowrap> :white_circle: 0.74%</td> <td nowrap> 328.77µs</td> <td nowrap> 333.12µs</td> <td nowrap> :white_circle: 2.01%</td> <td nowrap> :yellow_circle: 74%</td></tr><tr><td><tt>translate/</tt><br><tt>pulldown_cmark</td> <td nowrap> 3.63ms</td> <td nowrap> 3.65ms</td> <td nowrap> :white_circle: 0.53%</td> <td nowrap> 6.50ms</td> <td nowrap> 6.43ms</td> <td nowrap> :white_circle: -1.14%</td> <td nowrap> :yellow_circle: 76%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :white_circle: 0.22%</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :white_circle: 0.49%</td> <td nowrap> :green_circle: 0%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 4.85ms</td> <td nowrap> 4.88ms</td> <td nowrap> :white_circle: 0.80%</td> <td nowrap> 8.70ms</td> <td nowrap> 8.70ms</td> <td nowrap> :white_circle: 0.12%</td> <td nowrap> :yellow_circle: 78%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/4513198)

**Comment by Robbepop** [comment]
I think the removal of those checks is indeed correct.
From what I remember I added those duplicated checks when I was trying to mirror the Wasmtime API but didn't account for the fact that `wasmi` only provides a reduced API for Wasm module instantiation which renders those checks unnecessary.
Proper code review still needed though.

**Comment by yjhmelody** [comment]
Any problem?

**Comment by Robbepop** [comment]
> Any problem?

Proper code review still needed though.

**Comment by Robbepop** [comment]
The `wasmi::Module::instantiate` method was designed to kinda implement Wasmtime's `Instance::new`.
That is why it has those checks in place that are currently redundant in `wasmi` because `wasmi` only allows Wasm module instantiation via the `Linker` and does not (yet) have Wasmtime's `Instance::new` way because I think it is less user friendly and more error prone.

You are right that we should probably get rid of these duplicated checks.
However, benchmarks conclude that this isn't affecting performance significantly.
This is especially true for larger Wasm modules where the code section takes up the overwhelming majority of the entire validation process.

I think I would like to go with a different solution and maybe even signal unchecked-ness via `unsafe` keyword. However, `unsafe` at the same time is something I'd like to avoid. I will think about this.

**Review by Robbepop — COMMENTED** [review]
The `wasmi::Module::instantiate` method was designed to kinda implement Wasmtime's `Instance::new`.
That is why it has those checks in place that are currently redundant in `wasmi` because `wasmi` only allows Wasm module instantiation via the `Linker` and does not (yet) have Wasmtime's `Instance::new` way because I think it is less user friendly and more error prone.

You are right that we should probably get rid of these duplicated checks.
However, benchmarks conclude that this isn't affecting performance significantly.
This is especially true for larger Wasm modules where the code section takes up the overwhelming majority of the entire validation process.

I think I would like to go with a different solution and maybe even signal unchecked-ness via `unsafe` keyword. However, `unsafe` at the same time is something I'd like to avoid. I will think about this.

Another idea we should probably experiment with is to remove the checks in `process_import` instead since that is a user of `Module::instantiate` and thus a more likely candidate for checks removal in my opinion.

**Comment by Robbepop** [comment]
Closed due to inactivity.

**Pull request closed without merging**
